[build-system]
requires = [
    'setuptools>=40.8.0',
    'wheel',
    'oldest-supported-numpy',
    ]

[tool.cibuildwheel]
before-all = "apt install libpng-dev"

build-backend = "setuptools.build_meta"

